<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Pesanan_model extends CI_Model
{

    public $table = 'pesanan';
    public $id = 'id_pesanan';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json()
    {
        $this->datatables->select('id_pesanan,id_pengirim,id_kurir,id_metodePembayaran,status,penerima,alamat,no_telp,tgl_pesanan,keterangan');
        $this->datatables->from('pesanan');
        //add this line for join
        //$this->datatables->join('table2', 'pesanan.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('pesanan/read/$1'), 'Read') . " | " . anchor(site_url('pesanan/update/$1'), 'Update') . " | " . anchor(site_url('pesanan/delete/$1'), 'Delete', 'onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_pesanan');
        return $this->datatables->generate();
    }


    // insert data
    function insert($data)
    {
        // start transaction
        $this->db->trans_start();
        // $this->db->insert($this->table, $data);

        // 1. insert ke pesanan
        // 2. get id pesanan yang baru di insert
        // 3. insert ke detail_pesanan dengan isi id_pesanan yg baru di insert
        // 4. kurang qty pada detail_produk, sesuai



        // end transaction
        $this->db->trans_complete();

        if ($this->db->trans_status() === FALSE) {
            // Something went wrong
            $this->db->trans_rollback(); //rollback
            return FALSE;
        } else {
            // Committing data to the database.
            $this->db->trans_commit();
            return "success";
        }
    }


    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
}

/* End of file Pesanan_model.php */
/* Location: ./application/models/Pesanan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-06-04 08:48:01 */
/* http://harviacode.com */