<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Supplier_model extends CI_Model
{

    public $table = 'supplier';
    public $id = 'id_supplier';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json()
    {
        $this->datatables->select('id_supplier,nama_supplier,alamat,no_telp,email,image');
        $this->datatables->from('supplier');
        //add this line for join
        //$this->datatables->join('table2', 'supplier.field = table2.field');

        $this->datatables->add_column(
            'action',
            '<div class="btn-group">' .
                form_open('master/Supplier/read/$1') .
                form_button(['type' => 'submit', 'title' => 'Detail', 'class' => 'btn btn-primary', 'content' => '<i class="fas fa-info-circle"> </i>']) .
                form_close() . "&nbsp;" .
                form_open('master/Supplier/update/$1') .
                form_button(['type' => 'submit', 'title' => 'Edit', 'class' => 'btn btn-warning', 'content' => '<i class="fas fa-pencil-alt"> </i>']) .
                form_close() . "&nbsp;" .
                form_open('master/Supplier/delete/$1') .
                form_button(['type' => 'submit', 'title' => 'Hapus', 'class' => 'btn btn-danger'], '<i class="fas fa-trash-alt"> </i>', 'onclick="javascript: return confirm(\'Are You Sure ?\')"') .
                form_close() . '</div>',
            'id_supplier'
        );


        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('id_supplier', $q);
        $this->db->or_like('nama_supplier', $q);
        $this->db->or_like('alamat', $q);
        $this->db->or_like('no_telp', $q);
        $this->db->or_like('email', $q);
        $this->db->or_like('image', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_supplier', $q);
        $this->db->or_like('nama_supplier', $q);
        $this->db->or_like('alamat', $q);
        $this->db->or_like('no_telp', $q);
        $this->db->or_like('email', $q);
        $this->db->or_like('image', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
}

/* End of file Supplier_model.php */
/* Location: ./application/models/Supplier_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-05-19 06:12:53 */
/* http://harviacode.com */